config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/logout', to: 'sessions#destroy'

  root 'projects#index'
  resources :projects, except: :destroy
  get '/projects/:id/download', to: 'projects#download', as: :download_project
  get '/projects/:id/style_guide', to: 'projects#style_guide', as: :style_guide
  patch '/projects/:id/style_guide', to: 'projects#update_style_guide'
  put '/projects/:id/style_guide', to: 'projects#update_style_guide'
  resources :users
  resources :project_memberships, only: [:create, :destroy]
  resources :scripts, only: [:edit, :update]
  get '/scripts/:id/version/:version', to: 'scripts#version', as: :version_of_script
  get '/scripts/:id/compare/:first..:second', to: 'scripts#compare', as: :diff_script
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/script.rb
class Script < ApplicationRecord
  belongs_to :project
  has_many :cached_notes, -> { order line: :asc }
  
  scope :with_note_count, -> { left_joins(:cached_notes)
                               .group("scripts.id")
                               .select("scripts.*, count(cached_notes.id) as note_count") }
  
  before_save :strip_carriage_returns
  after_save :update_note_cache
  
  audited associated_with: :project
  
  validates :name, presence: true,
                   length: { maximum: 191 },
                   uniqueness: { scope: :project, case_sensitive: false }
  validates :text, presence: true
  validates :stage, presence: true,
                    inclusion: { in: %w(untouched translation tlc editing review finalised) }
                    
private
  # These mess with diffs
  def strip_carriage_returns
    text.delete! "\r"
  end
  
  def update_note_cache
    cached_notes.destroy_all
    lines = text.split "\n"
    lines.each_with_index do |text, number|
      if text.start_with? "//note("
        begin
          # TODO bring this into one regex
          matches_without_link = text.scan(/^\/\/note\((.*),\s*(.+)\):(.*)/)
          matches_with_link = text.scan(/^\/\/note\((.*),\s*(.+),\s*([a-z0-9]{6})\):(.*)/)
          if matches_with_link.count == 1 && matches_with_link[0].count == 4
            cached_notes.create(user: User.find_by(name: matches_with_link[0][0]),
                                added_at: Time.parse(matches_with_link[0][1]),
                                link: matches_with_link[0][2],
                                line: number,
                                text: matches_with_link[0][3].strip)
          elsif matches_without_link.count == 1 && matches_without_link[0].count == 3
            cached_notes.create(user: User.find_by(name: matches_without_link[0][0]),
                                added_at: Time.parse(matches_without_link[0][1]),
                                line: number,
                                text: matches_without_link[0][2].strip)
          end
        rescue
          # ignore this line
        end
      end
    end
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script
  before_action :get_permissions
  # edit shows script as read-only without write access
  before_action :require_read_access
  before_action :require_write_access, only: :update
  
  def edit
    set_audit_comment
  end

  def version
    @audit = @script.audits[params[:version].to_i - 1]
    set_audit_comment
    @script = @audit.revision
    @can_write = false
    render :edit
  end

  def compare
    @first = @script.audits[params[:first].to_i - 1]
    @second = @script.audits[params[:second].to_i - 1]
    @diff = Diffy::SplitDiff.new(@first.revision.text,
                                 @second.revision.text,
                                 format: :html,
                                 context: 5,
                                 include_plus_and_minus_in_html: true,
                                 include_diff_info: true)
  end

  def update
    set_audit_comment
    # TODO: use validations
    # TODO: support validation errors (update returns false) *and* outside exceptions
    begin
      @script.update(script_params)
      redirect_to edit_script_path(@script), notice: 'Script was successfully updated.'
    rescue => e
      flash.now[:danger] = "There was an error saving your changes. If this persists please save your work locally and contact an administrator."
      logger.error e
      render :edit
    end
  end
  
private
  def set_script
    if params[:action].in? ['edit', 'version']
      @script = Script.includes(:audits).find(params[:id])
    else
      @script = Script.find(params[:id])
    end
  end
  
  def script_params
    params.require(:script).permit(:text, :stage, :audit_comment)
  end
  
  def set_audit_comment
    if @audit.present?
      @audit_comment = @audit.comment
    elsif params[:script].present?
      @audit_comment = params[:script][:audit_comment]
    end
  end
  
  def get_permissions
    @can_read = current_user.can_read? @script.project
    @can_write = current_user.can_write? @script.project
  end
  
  def require_read_access
    redirect_to root_path unless @can_read
  end
  
  def require_write_access
    redirect_to root_path unless @can_write
  end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_diff_side.html.erb
<div class="col-md-6 diff_side">
  <div class="row with_avatar">
    <aside class="avatar">
      <%= avatar_for side[:audit].user %>
    </aside>
    <section class="content">
      <h4><%= link_to_script_version(side[:audit]) %></h4>
      <h5>Stage: <%= friendly_stage_names[side[:audit].revision.stage] %></h5>
      <h5><em><%= display_time(side[:audit].created_at) %></em></h5>
      <% if side[:audit].user.present? %>
        <h5>Edited by <%= link_to side[:audit].user.name, side[:audit].user %></h5>
      <% end %>
    </section>
  </div>
  <% unless side[:diff].blank? %>
    <%= raw side[:diff] %>
  <% end %>
</div>

app/views/scripts/_version_history.html.erb
<ul id="version_history" class="panel_list">
  <% @script.audits.reverse.each do |audit| %>
    <li class="panel panel-default with_avatar">
      <aside class="avatar">
        <%= avatar_for audit.user %>
      </aside>
      <section class="content">
        <p>
          <strong><%= link_to_script_version(audit) %></strong>
          - Stage: <strong><%= friendly_stage_names[audit.revision.stage] %></strong>
          <% unless audit.version == (@script.version || @script.audits.count) %>
            <%= link_to "(diff)", diff_script_path(id: @script.id,
                                                   first: audit.version,
                                                   second: @script.version || @script.audits.count) %>
          <% end %>
          <br><em><%= display_time(audit.created_at) %></em>
        </p>
        <% if audit.user.present? %>
          <p>
            Edited by <%= link_to audit.user.name, audit.user %>
          </p>
        <% end %>
        <% if audit.comment.present? %>
          <p>
            <strong>Comment:</strong> <%= parsed_comment(audit) %>
          </p>
        <% end %>
      </section>
    </li>
  <% end %>
</ul>

app/views/scripts/compare.html.erb
<% provide(:title, "Comparing v#{@first.version}, v#{@second.version} - #{@script.name}") %>
<div class="row"><h3><%= @script.name %></h3></div>

<div class="row">
  <%= render "diff_side", side: { audit: @first, diff: @diff.left } %>
  <%= render "diff_side", side: { audit: @second, diff: @diff.right } %>
</div>

app/views/scripts/edit.html.erb
<% provide(:title, @script.name) %>
<div class="row">
  <h3><%= @script.name %></h3>
  <% unless @audit.nil? %>
    <h4>Version <%= @script.version %> (<%= @audit.created_at %>)</h4>
    <h4><%= link_to "Back to current version", edit_script_path(@script) %></h4>
  <% end %>
</div>

<div id="script_editor_row" class="row">
  <div id="script_editor_container">
    <%= form_with(model: @script, local: true, id: "script_form") do |form| %>
      <% if @script.errors.any? %>
        <div class="alert alert-danger">
          <b><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</b>
    
          <ul>
          <% @script.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <% if @audit.nil? %>
        <p class="btn-group">
          <button id="increase_font_size" type="button" class="btn btn-default"><%= raw(glyphicon "plus") %>Increase font size</button>
          <button id="decrease_font_size" type="button" class="btn btn-default"><%= raw(glyphicon "minus") %>Decrease font size</button>
          <button id="add_note_before_line" type="button" class="btn btn-default"><%= raw(glyphicon "tag") %>Add note before line</button>
          <button id="toggle_note_pane" type="button" class="btn btn-default"><%= raw(glyphicon "tags") %>Toggle note pane</button>
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#style_guide_modal"><%= raw(glyphicon "education") %>Style guide</button>
        </p>
      <% end %>
      <%= form.text_area :text, id: "script_hidden", style: "display: none"; %>
      <div id="script_editor"></div>
      <div class="form-group">
        <%= form.label :stage %>
        <%= form.collection_select :stage,
                                    friendly_stage_names,
                                    :first,
                                    :second,
                                    {},
                                    class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :audit_comment, "Comment for change" %>
        <%= form.text_area(:audit_comment, value: @audit_comment, class: 'form-control') %>
      </div>
    
      <% if @can_write %>
        <%= button_tag class: 'btn btn-primary' do %>
          <%= raw(glyphicon "floppy-disk") %>
          Save changes
        <% end %>
      <% end %>
    <% end %>
    </div>
  <% if @audit.nil? %>
    <div id="script_note_pane">
      <h3>Notes</h3>
      <% if @script.cached_notes.any? %>
        <ul class="panel_list">
          <% @script.cached_notes.each do |note| %>
            <li class="panel panel-default with_avatar">
              <aside class="avatar">
                <%= avatar_for note.user %>
              </aside>
              <section class="content">
                <p>
                  <strong><%= link_to note.user.name, note.user %></strong>
                  <br><em><%= display_time(note.added_at) %></em>
                </p>
                <p>
                  <%= note.text %>
                </p>
                <p>
                  <% if note.link.present? %>
                    <%= link_to "Go to line (originally #{note.line + 1})", "javascript:goToNote('#{note.link}');" %>
                  <% else %>
                    <%= link_to "Line #{note.line + 1}", "javascript:goToLine(#{note.line + 1});" %>
                  <% end %>
                </p>
              </section>
            </li>
          <% end %>
        </ul>
      <% else %>
        none
      <% end %>
    </div>
  <% end %>
</div>

<hr>

<div class="row">
  <h3>Version history</h3>
  <%= render "version_history" %>
</div>

<div class="modal fade" id="style_guide_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @script.project.name %> Style Guide</h4>
      </div>
      <div class="modal-body">
        <%= markdown(@script.project.style_guide) %>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var editor = ace.edit("script_editor");
    editor.setTheme("ace/theme/twilight");
    editor.getSession().setMode("ace/mode/tlstatus<%= @script.project.language.downcase %>");
    editor.setOptions({
      autoScrollEditorIntoView: true,
      showPrintMargin: false,
      <% unless @can_write %>readOnly: true,<% end %>
    });
    editor.setValue($("#script_hidden").val());
    editor.clearSelection();
    editor.getSession().setUseWrapMode(true);
    editor.getSession().setUndoManager(new ace.UndoManager()); // setValue is undoable otherwise
    $("#script_editor").resizable({
      resize: function(event, ui) {
        editor.resize();
      }
    });
    $("#script_form").submit(function() {
      $("#script_hidden").val(editor.getValue());
      $(window).off('beforeunload');
    });
    $("#increase_font_size").click(function() {
      var fontSize = parseInt($("#script_editor").css("font-size"));
      fontSize = fontSize + 1 + "px";
      $("#script_editor").css({'font-size':fontSize});
      editor.focus();
    });
    $("#decrease_font_size").click(function() {
      var fontSize = parseInt($("#script_editor").css("font-size"));
      fontSize = fontSize - 1 + "px";
      $("#script_editor").css({'font-size':fontSize});
      editor.focus();
    });
    $("#add_note_before_line").click(function() {
      curRow = editor.selection.getCursor().row + 1;
      editor.gotoLine(curRow);
      editor.splitLine();
      
      var note = "//note(";
      note += "<%= current_user.name %>";
      note += ", ";
      note += new Date().toISOString();
      note += ", ";
      // link
      note += Math.random().toString(36).substr(2,6);
      note += "): ";
      
      editor.insert(note);
      editor.focus();
    });
    $("#toggle_note_pane").click(function() {
      $("#script_editor_row").toggleClass("script_editor_two_pane");
      editor.resize();
      editor.focus();
    });
    window.goToLine = function(line) {
      editor.gotoLine(line);
      editor.focus();
    };
    window.goToNote = function(link) {
      Range = require("ace/range").Range;
      editor.find(link, {
        start: new Range(0,0,0,0)
      });
      // clear selection
      curRow = editor.selection.getCursor().row + 1;
      editor.gotoLine(curRow);
    };
    window.goToHash = function() {
      if (window.location.hash.startsWith("#line_")) {
        var line_number = parseInt(window.location.hash.slice(6));
        window.goToLine(line_number);
        window.location.hash = "";
      }
    };
    window.goToHash();
    $(window).bind('hashchange', goToHash);

    $(window).on('beforeunload', function() {
      if (!editor.getSession().getUndoManager().hasUndo()) return undefined;
      
      return "You have unsaved changes! Are you sure you want to leave?";
    });
  });
</script>