config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/logout', to: 'sessions#destroy'

  root 'projects#index'
  resources :projects, except: :destroy
  get '/projects/:id/download', to: 'projects#download', as: :download_project
  get '/projects/:id/style_guide', to: 'projects#style_guide', as: :style_guide
  patch '/projects/:id/style_guide', to: 'projects#update_style_guide'
  put '/projects/:id/style_guide', to: 'projects#update_style_guide'
  resources :users
  resources :project_memberships, only: [:create, :destroy]
  resources :scripts, only: [:edit, :update]
  get '/scripts/:id/version/:version', to: 'scripts#version', as: :version_of_script
  get '/scripts/:id/compare/:first..:second', to: 'scripts#compare', as: :diff_script
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :project_memberships, dependent: :destroy
  has_many :cached_notes
  has_attached_file :avatar, styles: { thumb: "70x70#" }
  
  validates :name, presence: true, length: { maximum: 191 }, uniqueness: true
  validates :discord_uid, presence: true, length: { maximum: 20 }, uniqueness: true, numericality: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  def self.where_not_member_of_project(project)
    self.where(ProjectMembership.where('project_id = ? AND user_id = users.id', project.id).exists.not)
  end
  
  def can_read?(project)
    self.admin? || !!self.project_memberships.find_by(project: project)
  end
  
  def can_write?(project)
    self.admin? || self.project_memberships.find_by(project: project).write_access?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @membership = ProjectMembership.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # yeah I know this isn't ideal
    # a lot of stuff here isn't
    if params[:remove_avatar]
      @user.avatar = nil
    end
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :discord_uid, :admin, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, html: { multipart: true }) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <b><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</b>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :discord_uid %>
    <%= form.text_field :discord_uid, id: :user_discord_uid, class: 'form-control' %>
  </div>

  <div class="checkbox">
    <%= form.label :admin do |label| %>
      <%= form.check_box :admin, id: :user_admin %>
      Admin?
    <% end %>
  </div>
  
  <div class="checkbox">
    <%= label_tag :remove_avatar do |label| %>
      <%= check_box_tag :remove_avatar %> Remove avatar?
    <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editing User #{@user.name}") %>
<div class="row">
  <h3>Editing User</h3>
  
  <%= render 'form', user: @user %>
  
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<div class="row">
  <h3>Users</h3>
  
  <table width="100%" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Admin?</th>
        <% if current_user.admin? %><th colspan="2"></th><% end %>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><strong><%= link_to user.name, user %></strong></td>
          <td><%= user.admin %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <% if current_user.admin? %><%= link_to 'New User', new_user_path %><% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<div class="row">
  <h3>New User</h3>
  
  <%= render 'form', user: @user %>
  
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<% provide(:title, "User #{@user.name}") %>
<section class="user_profile row with_avatar">
  <aside class="avatar">
    <%= avatar_for @user %>
  </aside>
  <section class="content">
    <h3><%= @user.name %></h3>
    <p>
      <strong>Discord uid:</strong>
      <%= @user.discord_uid %>
    </p>
    <p>
      <strong>Admin:</strong>
      <%= @user.admin %>
    </p>
  </section>
</section>

<hr>

<section class="row" id="user_memberships">
  <h3>Projects</h3>
  <p>
    <% if @user.project_memberships.any? %>
      <ul>
        <% @user.project_memberships.each do |membership| %>
          <li>
            <% if current_user.can_read? membership.project %>
              <%= link_to membership.project.name, project_path(membership.project) %>
              <% unless membership.position.blank? %>(<%= membership.position %>)<% end %>
              <% unless membership.write_access? %>(read only)<% end %>
              <% if current_user.admin? %>
                <%= link_to '(remove)', membership, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            <% else %>
              [REDACTED]
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      none
    <% end %>
  </p>
  <% if current_user.admin? %>
    <p class="clearfix"><hr>
      <%= form_with(model: @membership, class: "form-horizontal", local: true) do |form| %>
        <%= form.hidden_field :user_id, value: @user.id %>
        <div class="form-group">
          <%= form.label :project_id, "Project", class: "control-label col-xs-2" %>
          <div class="col-xs-10">
            <%= form.collection_select :project_id, 
                                        Project.where_user_is_not_member(@user),
                                        :id,
                                        :name,
                                        {},
                                        class: "form-control input-sm" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :position, class: "control-label col-xs-2" %>
          <div class="col-xs-10">
            <%= form.text_field :position, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-offset-2 col-xs-10">
            <div class="checkbox">
              <%= form.label :write_access do %>
                <%= form.check_box :write_access %>
                Write access?
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-offset-2 col-xs-10">
             <%= form.submit "Add to project", class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      <% end %>
      </p>
    <% end %>
</section>

<div class="row">
  <% if current_user.admin? %><%= link_to 'Edit', edit_user_path(@user) %><% end %>
</div>