config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/logout', to: 'sessions#destroy'

  root 'projects#index'
  resources :projects, except: :destroy
  get '/projects/:id/download', to: 'projects#download', as: :download_project
  get '/projects/:id/style_guide', to: 'projects#style_guide', as: :style_guide
  patch '/projects/:id/style_guide', to: 'projects#update_style_guide'
  put '/projects/:id/style_guide', to: 'projects#update_style_guide'
  resources :users
  resources :project_memberships, only: [:create, :destroy]
  resources :scripts, only: [:edit, :update]
  get '/scripts/:id/version/:version', to: 'scripts#version', as: :version_of_script
  get '/scripts/:id/compare/:first..:second', to: 'scripts#compare', as: :diff_script
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_memberships, dependent: :destroy
  has_many :scripts, dependent: :destroy
  has_many :cached_notes, through: :scripts
  
  has_associated_audits
  
  validates :name, presence: true, length: { maximum: 191 }, uniqueness: true
  validates :language, presence: true, inclusion: { in: %w(nss) }
  
  def self.where_user_is_not_member(user)
    self.where(ProjectMembership.where('project_id = projects.id AND user_id = ?', user.id).exists.not)
  end
  
  def story_scripts
    scripts.where(story: true)
  end
  
  def completion_counts
    return @counts unless @counts.nil?
    @counts = {}
    @counts['finalised'] = story_scripts.where(stage: 'finalised').size
    @counts['review'] = @counts['finalised'] + story_scripts.where(stage: 'review').size
    @counts['editing'] = @counts['review'] + story_scripts.where(stage: 'editing').size
    @counts['tlc'] = @counts['editing'] + story_scripts.where(stage: 'tlc').size
    @counts['translation'] = @counts['tlc'] + story_scripts.where(stage: 'translation').size
    return @counts
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy, :download, :style_guide, :update_style_guide]
  before_action :require_read_access, only: [:show, :download]
  before_action :require_write_access, only: [:update_style_guide]
  
  # GET /projects
  # GET /projects.json
  def index
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @scripts = @project.scripts.with_note_count
    @membership = ProjectMembership.new
    @changes = @project.associated_audits.where(auditable_type: "Script", action: :update)
                                         .order(created_at: :desc)
                                         .paginate(page: params[:page],
                                                   per_page: 10)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end
  
  def download
    time = Time.zone.now
    buf = Zip::OutputStream.write_buffer do |zio|
      zio.comment = "Generated #{time}"
      @project.scripts.each do |script|
        zio.put_next_entry script.name
        zio.write script.text
      end
    end
    buf.rewind
    send_data buf.read, filename: "#{@project.name}_#{time.to_i}.zip"
  end
  
  def style_guide
  end
  
  def update_style_guide
    if @project.update(style_guide_params)
      redirect_to style_guide_path(@project), notice: 'Style guide was successfully updated.'
    else
      render :style_guide
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :language)
    end
    
    def style_guide_params
      params.require(:project).permit(:style_guide)
    end
    
    def require_read_access
      redirect_to root_path unless current_user.can_read? @project
    end
    
    def require_write_access
      redirect_to root_path unless current_user.can_write? @project
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <b><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</b>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :language %>
    <%= form.text_field :language, id: :project_language, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, "Editing Project #{@project.name}") %>
<div class="row">
  <h3>Editing Project</h3>
  
  <%= render 'form', project: @project %>
  
  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
<div class="row">
  <h3>Projects</h3>
  
  <table width="100%" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Language</th>
      </tr>
    </thead>
  
    <tbody>
      <% @visible_projects.each do |project| %>
        <tr>
          <td><strong><%= link_to project.name, project %></strong></td>
          <td><%= project.language %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <% if current_user.admin? %><%= link_to 'New Project', new_project_path %><% end %>
</div>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>
<div class="row">
  <h3>New Project</h3>
  
  <%= render 'form', project: @project %>
  
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<% provide(:title, "Project #{@project.name}") %>
<div class="row">
  <section class="col-md-6">
    <h3><%= @project.name %></h3>
    <p>
      <strong>Language:</strong> <%= @project.language %>
      <br><strong>Total scripts:</strong> <%= @project.scripts.size %>
      <br><strong>Story scripts:</strong> <%= @project.story_scripts.size %>
      <% if current_user.admin? %><br><%= link_to 'Edit', edit_project_path(@project) %><% end %>
      <% if @project.story_scripts.size > 0 %>
        <p>
          <h4>Completion counts</h4>
          <p>These are cumulative (e.g. "TLC" includes all scripts that are <em>at least</em> in TLC stage)</p>
          <% {'translation' => '',
              'tlc' => ' progress-bar-info',
              'editing' => ' progress-bar-success',
              'review' => ' progress-bar-warning',
              'finalised' => ' progress-bar-danger'}.each do |stage, cls| %>
            <div class="row">
              <div class="col-sm-3"><strong><%= friendly_stage_names[stage] %></strong>: <%= @project.completion_counts[stage] %> / <%= @project.story_scripts.size %></div>
              <div class="col-sm-9"><div class="progress stage_progress"><div class="progress-bar<%= cls %>" style="width: <%= (@project.completion_counts[stage].to_f / @project.story_scripts.size) * 100 %>%"></div></div></div>
            </div>
          <% end %>
        </p>
      <% end %>
      <p>
        <%= link_to raw("#{glyphicon 'download-alt'} Download ZIP"),
                        download_project_path(@project),
                        class: 'btn btn-primary' %>
        <%= link_to raw("#{glyphicon 'education'} Style Guide"),
                        style_guide_path(@project),
                        class: 'btn btn-primary' %>
      </p>
    </p>
  </section>
  <section class="col-md-6" id="project_members">
    <h3>Members</h3>
    <% if @project.project_memberships.any? %>
      <ul class="panel_list clearfix">
        <% @project.project_memberships.each do |membership| %>
          <li class="panel panel-default with_avatar col-md-5<%= membership.write_access? ? "" : " membership_read_only invisible" %>">
            <aside class="avatar">
              <%= avatar_for membership.user %>
            </aside>
            <section class="content">
              <strong><%= link_to membership.user.name, membership.user %></strong>
              <% unless membership.position.blank? %><br><em><%= membership.position %></em><% end %>
              <% unless membership.write_access? %><br>(read only)<% end %>
              <% if current_user.admin? %>
                <br><%= link_to '(remove)', membership, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </section>
          </li>
        <% end %>
      </ul>
    <% else %>
      none
    <% end %>
    <p><%= link_to "toggle read only", "#", id: "toggle_read_only" %></p>
    <% if current_user.admin? %>
      <p><hr>
      <%= form_with(model: @membership, class: "form-horizontal", local: true) do |form| %>
        <%= form.hidden_field :project_id, value: @project.id %>
        <div class="form-group">
          <%= form.label :user_id, "User", class: "control-label col-xs-2" %>
          <div class="col-xs-10">
            <%= form.collection_select :user_id, 
                                        User.where_not_member_of_project(@project),
                                        :id,
                                        :name,
                                        {},
                                        class: "form-control input-sm" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :position, class: "control-label col-xs-2" %>
          <div class="col-xs-10">
            <%= form.text_field :position, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-offset-2 col-xs-10">
            <div class="checkbox">
              <%= form.label :write_access do %>
                <%= form.check_box :write_access %>
                Write access?
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-xs-offset-2 col-xs-10">
             <%= form.submit "Add to project", class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      <% end %>
      </p>
    <% end %>
  </section>
</div>

<hr>

<div class="row">
  <h3>Files</h3>
  <p><label><input type="checkbox" id="check_only_with_notes" class="scripts_table_filter"> Only with notes</label></p>
  <p><label><input type="checkbox" id="check_only_story_scripts" class="scripts_table_filter" checked> Only story scripts</label></p>
  <p>
    <table width="100%">
      <tr>
        <td><label><input type="checkbox" id="check_all_stages" class="scripts_table_filter" checked> All</label></td>
        <% friendly_stage_names.each_value do |stage| %>
          <td><label><input type="checkbox" class="scripts_table_filter stages_checkbox" data-stage="<%= stage %>" checked> <%= stage %></label></td>
        <% end %>
      </tr>
    </table>
  </p>
  <table width="100%" class="table" id="scripts_table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Stage</th>
        <th>Note count</th>
        <th>Last change</th>
      </tr>
    </thead>
    <tbody>
      <% @scripts.each do |script| %>
        <tr data-story="<%= script.story? %>">
          <td><strong><%= link_to script.name, edit_script_path(script) %></strong></td>
          <td><%= friendly_stage_names[script.stage] %></td>
          <td><%= script.note_count %></td>
          <td data-order="<%= script.updated_at.to_i %>"><%= display_time(script.updated_at) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<hr>

<div class="row">
  <h3>Recent changes</h3>
  <% if @changes.any? %>
    <ul class="panel_list">
      <% @changes.each do |change| %>
        <li class="panel panel-default with_avatar">
          <aside class="avatar">
            <%= avatar_for change.user %>
          </aside>
          <section class="content">
            <p>
              <em><%= display_time(change.created_at) %></em>
              <% if change.user.present? %>
                <br><strong><%= link_to change.user.name, change.user %></strong> updated
                <strong><%= link_to change.auditable.name, edit_script_path(change.auditable) %></strong>
              <% else %>
                <br><strong><%= link_to change.auditable.name, edit_script_path(change.auditable) %></strong> was updated
              <% end %>
            </p>
            <% if change.audited_changes.include? "stage" %>
              <p>
                <strong>Stage</strong> went from
                <strong><%= friendly_stage_names[change.audited_changes["stage"].first] %></strong>
                to <strong><%= friendly_stage_names[change.audited_changes["stage"].second] %></strong>
              </p>
            <% end %>
            <% if change.comment.present? %>
              <p>
                <strong>Comment:</strong> <%= parsed_comment(change) %>
              </p>
            <% end %>
            <p>
              <strong><%= link_to_script_version(change) %></strong>
              <% unless change.version == 1 %>
                <%= link_to "(diff to previous)",
                                    diff_script_path(id: change.auditable.id, first: change.version - 1, second: change.version) %>
              <% end %>
            </p>
          </section>
        </li>
      <% end %>
    </ul>
  <% else %>
    none
  <% end %>
  
  <%= will_paginate @changes %>
</div>


<script type="text/javascript">
  $(document).ready(function() {
    var table = $('#scripts_table').DataTable({
      "info": false
    });
    var lock = false;
    $('.scripts_table_filter').change(function() {
      if (!lock) table.draw();
    });
    $('#check_all_stages').change(function() {
      lock = true;
      $(".stages_checkbox").prop('checked', $(this).prop("checked"));
      table.draw();
      lock = false;
    });
    $.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
      if($("#check_only_with_notes")[0].checked && parseInt(data[2], 10) == 0) return false;
      if($("#check_only_story_scripts")[0].checked && $(settings.aoData[dataIndex].nTr).data('story') == false) return false;
      
      var checked_stages = [];
      $('.stages_checkbox').each(function() {
        if($(this)[0].checked) checked_stages.push($(this).data('stage'));
      });
      if(checked_stages.includes(data[1])) return true;
    
      return false;
    });
    $("#toggle_read_only").click(function() {
      $(".membership_read_only").toggleClass("invisible");
    });
    
    table.draw(); // to apply initial story script filter
  });
</script>

app/views/projects/style_guide.html.erb
<% provide(:title, "#{@project.name} Style Guide") %>
<div class="row">
  <h3><%= @project.name %> Style Guide</h3>
  <% unless @project.style_guide.blank? %>
    <hr>
    <%= markdown(@project.style_guide) %>
  <% end %>
  
  <% if current_user.can_write? @project %>
    <hr>
    <h3>Edit</h3>
    <%= form_with(model: @project, local: true, url: style_guide_path(@project)) do |form| %>
      <div class="form-group">
        <%= form.text_area :style_guide, rows: 30, class: 'form-control', style: 'width: 100%' %>
      </div>
      <%= form.submit "Update style guide", class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>