config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'
  get '/logout', to: 'sessions#destroy'

  root 'projects#index'
  resources :projects, except: :destroy
  get '/projects/:id/download', to: 'projects#download', as: :download_project
  get '/projects/:id/style_guide', to: 'projects#style_guide', as: :style_guide
  patch '/projects/:id/style_guide', to: 'projects#update_style_guide'
  put '/projects/:id/style_guide', to: 'projects#update_style_guide'
  resources :users
  resources :project_memberships, only: [:create, :destroy]
  resources :scripts, only: [:edit, :update]
  get '/scripts/:id/version/:version', to: 'scripts#version', as: :version_of_script
  get '/scripts/:id/compare/:first..:second', to: 'scripts#compare', as: :diff_script
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% unless Rails.env.production? %>(DEVELOPMENT)<% end %>
      <%= yield :title %>
      - TLStatus
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style type="text/css">
      body:before {
        <% if Date.today.month == 9 && Date.today.day == 9 %>
          background-image: url(<%= image_url('backgrounds/nine.png') %>);
        <% # TODO: configurable %>
        <% elsif current_user.id == 15 %>
          background-image: url(<%= image_url('backgrounds/8.png') %>);
        <% else %>
          background-image: url(<%= image_url('backgrounds/' + rand(1..10).to_s + '.png') %>);
        <% end %>
      }
    </style>
    
    <script type="text/javascript"
            src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"
            data-turbolinks-track="reload"></script>
    <script type="text/javascript"
            src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"
            data-turbolinks-track="reload"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
  </head>

  <body <%= yield(:body_attributes) %>>
    <div class="navbar navbar-default<% unless Rails.env.production? %> navbar_development<% end %>">
      <div class="container-fluid full_page_width">
        <div class="navbar-header">
          <% # if you notice this please don't spoil the surprise for everyone else %>
          <% if Date.today.month == 9 && Date.today.day == 9 %>
            <%= link_to "Happy Cirno Day!", root_path, class: "navbar-brand" %>
          <% else %>
            <%= link_to "TLStatus", root_path, class: "navbar-brand" %>
          <% end %>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <% @visible_projects.each do |project| %>
              <li><%= link_to project do %><span class="tlstatus-icon icon-hoppy"></span> <%= project.name %><% end %></li>
            <% end %>
            <li><%= link_to raw("#{glyphicon 'folder-open'} All Projects"), projects_path %></li>
            <li><%= link_to raw("#{glyphicon 'user'} Users"), users_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to raw("#{glyphicon 'log-out'} Log out"), logout_path %></li>
          </ul>

        </div>
      </div>
    </div>
    
    <div class="container-fluid full_page_width">
      <% if flash.any? %>
        <section id="alerts">
          <% flash.each do |type, message| %>
            <div class="alert alert-<%= type %>"><%= message %></div>
          <% end %>
        </section>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>